/** Stable Phase 2A.2 reason codes. Every decision emits at least one. */
export const REASON = {
  PROG_LOAD_TOP_RANGE_RIR: 'PROG_LOAD_TOP_RANGE_RIR',
  PROG_LOAD_REPEATED_PERFORMANCE: 'PROG_LOAD_REPEATED_PERFORMANCE',
  BUILD_REPS_WITHIN_RANGE: 'BUILD_REPS_WITHIN_RANGE',
  HOLD_EXCESSIVE_EFFORT: 'HOLD_EXCESSIVE_EFFORT',
  HOLD_FIRST_NO_RIR_CONFIRMATION: 'HOLD_FIRST_NO_RIR_CONFIRMATION',
  HOLD_SINGLE_BAD_EXPOSURE: 'HOLD_SINGLE_BAD_EXPOSURE',
  HOLD_SUCCESSFUL_LOAD_STEP: 'HOLD_SUCCESSFUL_LOAD_STEP',
  HOLD_BODYWEIGHT_NO_EXTERNAL_LOAD: 'HOLD_BODYWEIGHT_NO_EXTERNAL_LOAD',
  HOLD_NON_REP_MEASUREMENT: 'HOLD_NON_REP_MEASUREMENT',
  REDUCE_REPEATED_BELOW_RANGE: 'REDUCE_REPEATED_BELOW_RANGE',
  INSUFFICIENT_SKIPPED: 'INSUFFICIENT_SKIPPED',
  INSUFFICIENT_PARTIAL: 'INSUFFICIENT_PARTIAL',
  INSUFFICIENT_NO_COUNTED_SETS: 'INSUFFICIENT_NO_COUNTED_SETS',
  INSUFFICIENT_NULL_SNAPSHOT: 'INSUFFICIENT_NULL_SNAPSHOT',
  PAIN_HOLD: 'PAIN_HOLD',
  REVIEW_PAIN_DISCOMFORT: 'REVIEW_PAIN_DISCOMFORT',
  REVIEW_CONFLICTING_SIGNAL: 'REVIEW_CONFLICTING_SIGNAL',
  REVIEW_ASSISTED_BODYWEIGHT: 'REVIEW_ASSISTED_BODYWEIGHT',
  NOTE_UNILATERAL_NO_SIDE_SPLIT: 'NOTE_UNILATERAL_NO_SIDE_SPLIT',
  NOTE_EXTRAS_EXCLUDED: 'NOTE_EXTRAS_EXCLUDED',
  NOTE_WARMUP_RAMP_EXCLUDED: 'NOTE_WARMUP_RAMP_EXCLUDED',
} as const;

export type ReasonCode = (typeof REASON)[keyof typeof REASON];

/** Actual RIR is compatible when it is not more than this below target. Easier (higher) RIR still qualifies. */
export const RIR_TOLERANCE = 0.5;

export const COMPARABLE_LOOKBACK_DAYS = 42;
export const COMPARABLE_MAX_EXPOSURES = 4;
export const POOR_EXPOSURES_BEFORE_REDUCE = 2;
export const POOR_EXPOSURES_BEFORE_REVIEW = 3;
