/** Stable Phase 2A.2 reason codes. Every decision emits at least one. */
export const REASON = {
  PROG_LOAD_TOP_RANGE_RIR: 'PROG_LOAD_TOP_RANGE_RIR',
  PROG_LOAD_UNDERCHALLENGED: 'PROG_LOAD_UNDERCHALLENGED',
  PROG_LOAD_REPEATED_PERFORMANCE: 'PROG_LOAD_REPEATED_PERFORMANCE',
  BUILD_REPS_WITHIN_RANGE: 'BUILD_REPS_WITHIN_RANGE',
  HOLD_EXCESSIVE_EFFORT: 'HOLD_EXCESSIVE_EFFORT',
  HOLD_FIRST_NO_RIR_CONFIRMATION: 'HOLD_FIRST_NO_RIR_CONFIRMATION',
  HOLD_SINGLE_BAD_EXPOSURE: 'HOLD_SINGLE_BAD_EXPOSURE',
  HOLD_SUCCESSFUL_LOAD_STEP: 'HOLD_SUCCESSFUL_LOAD_STEP',
  HOLD_BODYWEIGHT_NO_EXTERNAL_LOAD: 'HOLD_BODYWEIGHT_NO_EXTERNAL_LOAD',
  HOLD_NON_REP_MEASUREMENT: 'HOLD_NON_REP_MEASUREMENT',
  HOLD_COULD_NOT_COMPLETE: 'HOLD_COULD_NOT_COMPLETE',
  HOLD_BELOW_RANGE_UNDERCHALLENGED: 'HOLD_BELOW_RANGE_UNDERCHALLENGED',
  REDUCE_REPEATED_BELOW_RANGE: 'REDUCE_REPEATED_BELOW_RANGE',
  REDUCE_REPEATED_BELOW_RANGE_EXCESSIVE: 'REDUCE_REPEATED_BELOW_RANGE_EXCESSIVE',
  REVIEW_BELOW_RANGE_UNDERCHALLENGED: 'REVIEW_BELOW_RANGE_UNDERCHALLENGED',
  REVIEW_BELOW_RANGE_UNKNOWN_EFFORT: 'REVIEW_BELOW_RANGE_UNKNOWN_EFFORT',
  REVIEW_COULD_NOT_COMPLETE: 'REVIEW_COULD_NOT_COMPLETE',
  INSUFFICIENT_SKIPPED: 'INSUFFICIENT_SKIPPED',
  INSUFFICIENT_PARTIAL: 'INSUFFICIENT_PARTIAL',
  INSUFFICIENT_NO_COUNTED_SETS: 'INSUFFICIENT_NO_COUNTED_SETS',
  INSUFFICIENT_NULL_SNAPSHOT: 'INSUFFICIENT_NULL_SNAPSHOT',
  PAIN_HOLD: 'PAIN_HOLD',
  REVIEW_PAIN_DISCOMFORT: 'REVIEW_PAIN_DISCOMFORT',
  REVIEW_CONFLICTING_SIGNAL: 'REVIEW_CONFLICTING_SIGNAL',
  REVIEW_ASSISTED_BODYWEIGHT: 'REVIEW_ASSISTED_BODYWEIGHT',
  NOTE_UNILATERAL_NO_SIDE_SPLIT: 'NOTE_UNILATERAL_NO_SIDE_SPLIT',
  NOTE_EXTRAS_EXCLUDED: 'NOTE_EXTRAS_EXCLUDED',
  NOTE_WARMUP_RAMP_EXCLUDED: 'NOTE_WARMUP_RAMP_EXCLUDED',
} as const;

export type ReasonCode = (typeof REASON)[keyof typeof REASON];

/**
 * Target-compatible RIR band relative to prescribed target:
 *   [target - RIR_TOLERANCE_LOW, target + RIR_TOLERANCE_HIGH]
 * Target 2 → compatible 1.5–3.5. Below that is excessive. Above that is underchallenged.
 */
export const RIR_TOLERANCE_LOW = 0.5;
export const RIR_TOLERANCE_HIGH = 1.5;
/** @deprecated Use RIR_TOLERANCE_LOW. Kept so existing 2A.2 imports keep working. */
export const RIR_TOLERANCE = RIR_TOLERANCE_LOW;

export type RirBand = 'excessive' | 'compatible' | 'underchallenged';
export type EffortClass = RirBand | 'unknown' | 'mixed';

export function classifyRir(actual: number, target: number): RirBand {
  if (actual + RIR_TOLERANCE_LOW < target) return 'excessive';
  if (actual > target + RIR_TOLERANCE_HIGH) return 'underchallenged';
  return 'compatible';
}

export const COMPARABLE_LOOKBACK_DAYS = 42;
export const COMPARABLE_MAX_EXPOSURES = 4;
export const POOR_EXPOSURES_BEFORE_REDUCE = 2;
export const POOR_EXPOSURES_BEFORE_REVIEW = 3;
