/** Common S&C names → catalog names. Exact alias keys only — never steal a more specific lift. */
export const EXERCISE_ALIASES: Record<string, string> = {
  'bench press': 'Barbell Bench Press',
  'barbell bench': 'Barbell Bench Press',
  'flat bench': 'Barbell Bench Press',
  'db bench': 'Dumbbell Bench Press',
  'dumbbell bench': 'Dumbbell Bench Press',
  'incline db press': 'Incline Dumbbell Press',
  'incline press': 'Incline Dumbbell Press',
  'ohp': 'Overhead Press',
  'military press': 'Overhead Press',
  'dumbbell overhead press': 'Dumbbell Shoulder Press',
  'db overhead press': 'Dumbbell Shoulder Press',
  'db shoulder press': 'Dumbbell Shoulder Press',
  'chest-supported row': 'Dumbbell Row',
  'chest supported row': 'Dumbbell Row',
  'chest supported db row': 'Dumbbell Row',
  'db row': 'Dumbbell Row',
  'cable row': 'Seated Cable Row',
  'seated row': 'Seated Cable Row',
  'lat pull down': 'Lat Pulldown',
  'lat pull-down': 'Lat Pulldown',
  'pulldown': 'Lat Pulldown',
  'pull up': 'Pull-Up',
  'pullups': 'Pull-Up',
  'deadlift': 'Conventional Deadlift',
  'conv deadlift': 'Conventional Deadlift',
  'rdl': 'Romanian Deadlift',
  'barbell rdl': 'Romanian Deadlift',
  'light db rdl': 'Dumbbell RDL',
  'light dumbbell rdl': 'Dumbbell RDL',
  'db rdl': 'Dumbbell RDL',
  'trap bar dl': 'Trap Bar Deadlift',
  'hex bar deadlift': 'Trap Bar Deadlift',
  'split squat': 'Bulgarian Split Squat',
  'rear foot elevated split squat': 'Bulgarian Split Squat',
  'walking lunges': 'Walking Lunge',
  'goblet squats': 'Goblet Squat',
  'bb squat': 'Back Squat',
  'farmers carry': 'Farmer Carry',
  'farmer carries': 'Farmer Carry',
  'farmer\'s carry': 'Farmer Carry',
  'kb swing': 'Kettlebell Swing',
  'squat jump': 'Vertical Jump',
  'box jump': 'Vertical Jump',
  'mb chest pass': 'Medicine-Ball Chest Pass',
  'med ball chest pass': 'Medicine-Ball Chest Pass',
  'push up': 'Push-Up',
  'push-up + thoracic rotation': 'Push-Up to Toe Touch',
  'push-up to rotation': 'Push-Up to Toe Touch',
  'push up to rotation': 'Push-Up to Toe Touch',
  'band pulldown': 'Band Row',
  'band pull down': 'Band Row',
  'scapular wall slide': 'Scapular Push-Up',
  'wall slide': 'Scapular Push-Up',
};

export function aliasExerciseName(name: string): string {
  const key = String(name || '')
    .trim()
    .toLowerCase()
    .replace(/\s+/g, ' ');
  return EXERCISE_ALIASES[key] || name;
}
