import fs from "fs";
const p = "C:/Users/JesseTrowbridge/.cursor/projects/c-Users-JesseTrowbridge-OneDrive-Tegria-Documents-GitHub-builtiq/agent-tools/921689b7-4553-4754-8c8d-4306855b90d5.txt";
const t = fs.readFileSync(p, "utf8");
const lines = t.split(/\n/);
const info = [];
info.push("lines=" + lines.length);
info.push("chars=" + t.length);
info.push("first=" + lines[0].slice(0, 160));
info.push("second=" + (lines[1] || "").slice(0, 160));
info.push("last1=" + (lines[lines.length-1] || "").slice(0, 160));
info.push("last2=" + (lines[lines.length-2] || "").slice(0, 160));
info.push("last3=" + (lines[lines.length-3] || "").slice(0, 160));
info.push("last4=" + (lines[lines.length-4] || "").slice(0, 160));
const secret = /supabase|api_key|secret|password|openai|service_role|anon_key/i.test(t);
info.push("has_secret_word=" + secret);
const hits = fs.readFileSync("docs/catalog-overhaul/_tmp_agent_hits.txt", "utf8");
const tail = fs.readFileSync("docs/catalog-overhaul/_tmp_agent_tail.txt", "utf8");
const flat = fs.readFileSync("docs/catalog-overhaul/_tmp_flat_copy.txt", "utf8");
info.push("HITS_FILE=" + hits.replace(/\n/g, " || "));
info.push("TAIL_FILE=" + tail.replace(/\n/g, " || "));
info.push("FLAT_FILE=" + flat.replace(/\n/g, " || "));
fs.writeFileSync("docs/catalog-overhaul/_tmp_wrap_info.txt", info.join("\n"));
info.forEach(function(x) { console.log("BIQ " + x); });
