import type { QualityClassification } from '../scienceEngine/catalogEnrichment/qualityPass';

/** Explicit enrichment for new master cards added after BIQ-0213. */
export const NEW_MASTER_CLASSIFICATIONS: Record<string, QualityClassification> = {
  '261': {
    movement_pattern: 'horizontal_pull',
    primary_muscles: ['upper_back'],
    secondary_muscles: ['lats', 'biceps', 'rear_delts'],
    involved_muscles: ['upper_back', 'lats', 'biceps', 'rear_delts'],
    unmapped_muscle_labels: [],
    hypertrophy_volume_credits: [
      { muscle: 'upper_back', credit: 1 },
      { muscle: 'biceps', credit: 0.5 },
    ],
    volume_policy: 'strength_hypertrophy',
    laterality: 'bilateral',
    measurement_type: 'reps',
    exercise_kind: 'compound',
    fatigue_cost: 'medium',
    skill_demand: 'low',
    program_roles: ['secondary', 'accessory'],
    default_rep_min: 5,
    default_rep_max: 10,
    warmup_eligible: false,
    power_eligible: false,
    ramp_eligible: true,
    cooldown_eligible: false,
    demand_notes:
      'compound horizontal pull; medium fatigue; low skill; bilateral; reps measurement; volume policy strength_hypertrophy; hypertrophy credits upper_back:1, biceps:0.5',
    review_required: false,
    review_reasons: [],
    confidence: 'high',
    anomalies: [],
    primary_assignment: 'assigned',
  },
  '262': {
    movement_pattern: 'horizontal_push',
    primary_muscles: ['chest'],
    secondary_muscles: ['triceps', 'front_delts'],
    involved_muscles: ['chest', 'triceps', 'front_delts'],
    unmapped_muscle_labels: [],
    hypertrophy_volume_credits: [
      { muscle: 'chest', credit: 1 },
      { muscle: 'triceps', credit: 0.5 },
      { muscle: 'front_delts', credit: 0.5 },
    ],
    volume_policy: 'strength_hypertrophy',
    laterality: 'bilateral',
    measurement_type: 'reps',
    exercise_kind: 'compound',
    fatigue_cost: 'medium',
    skill_demand: 'low',
    program_roles: ['secondary', 'accessory'],
    default_rep_min: 5,
    default_rep_max: 10,
    warmup_eligible: false,
    power_eligible: false,
    ramp_eligible: true,
    cooldown_eligible: false,
    demand_notes:
      'compound horizontal push; medium fatigue; low skill; bilateral; reps measurement; volume policy strength_hypertrophy; hypertrophy credits chest:1, triceps:0.5, front_delts:0.5',
    review_required: false,
    review_reasons: [],
    confidence: 'high',
    anomalies: [],
    primary_assignment: 'assigned',
  },
  '263': {
    movement_pattern: 'vertical_push',
    primary_muscles: ['front_delts'],
    secondary_muscles: ['triceps', 'side_delts'],
    involved_muscles: ['front_delts', 'triceps', 'side_delts'],
    unmapped_muscle_labels: [],
    hypertrophy_volume_credits: [
      { muscle: 'front_delts', credit: 1 },
      { muscle: 'triceps', credit: 0.5 },
    ],
    volume_policy: 'strength_hypertrophy',
    laterality: 'bilateral',
    measurement_type: 'reps',
    exercise_kind: 'compound',
    fatigue_cost: 'medium',
    skill_demand: 'medium',
    program_roles: ['primary', 'secondary'],
    default_rep_min: 5,
    default_rep_max: 10,
    warmup_eligible: false,
    power_eligible: false,
    ramp_eligible: true,
    cooldown_eligible: false,
    demand_notes:
      'compound vertical push; seated; medium fatigue; medium skill; bilateral; reps measurement; volume policy strength_hypertrophy; hypertrophy credits front_delts:1, triceps:0.5',
    review_required: false,
    review_reasons: [],
    confidence: 'high',
    anomalies: [],
    primary_assignment: 'assigned',
  },
  '264': {
    movement_pattern: 'core_flexion',
    primary_muscles: ['abs'],
    secondary_muscles: ['hip_flexors'],
    involved_muscles: ['abs', 'hip_flexors'],
    unmapped_muscle_labels: [],
    hypertrophy_volume_credits: [{ muscle: 'abs', credit: 1 }],
    volume_policy: 'core',
    laterality: 'bilateral',
    measurement_type: 'reps',
    exercise_kind: 'isolation',
    fatigue_cost: 'medium',
    skill_demand: 'medium',
    program_roles: ['isolation', 'accessory'],
    default_rep_min: 8,
    default_rep_max: 15,
    warmup_eligible: false,
    power_eligible: false,
    ramp_eligible: false,
    cooldown_eligible: false,
    demand_notes:
      'isolation core flexion; medium fatigue; medium skill; bilateral; reps measurement; volume policy core; hypertrophy credits abs:1; GHD with feet anchored; distinct from floor Sit-Up and glute-ham raise',
    review_required: false,
    review_reasons: [],
    confidence: 'high',
    anomalies: [],
    primary_assignment: 'assigned',
  },
};

export function coachingFieldsFromClassification(proposed: QualityClassification): Record<string, unknown> {
  return {
    movement_pattern: proposed.movement_pattern,
    laterality: proposed.laterality,
    measurement_type: proposed.measurement_type,
    exercise_kind: proposed.exercise_kind,
    program_roles: proposed.program_roles,
    fatigue_cost: proposed.fatigue_cost === 'medium' ? 'moderate' : proposed.fatigue_cost,
    skill_demand: proposed.skill_demand === 'medium' ? 'moderate' : proposed.skill_demand,
    warmup_eligible: proposed.warmup_eligible,
    power_eligible: proposed.power_eligible,
    ramp_eligible: proposed.ramp_eligible,
    cooldown_eligible: proposed.cooldown_eligible,
    default_rep_min: proposed.default_rep_min,
    default_rep_max: proposed.default_rep_max,
    volume_policy: proposed.volume_policy,
    hypertrophy_volume_credits: proposed.hypertrophy_volume_credits,
    primary_muscles: proposed.primary_muscles,
    secondary_muscles: proposed.secondary_muscles,
    involved_muscles: proposed.involved_muscles,
    primary_assignment: proposed.primary_assignment,
    demand_notes: proposed.demand_notes,
    demand_characteristics: [],
    enrichment_version: 'BIQ-0213',
  };
}
